import 'referral_lang_constants.dart';

class ReferralMrIn {
  static Map<String, String> get translations => {
        ReferralLangConstants.headReferAndEarn: 'रेफर करा आणि कमवा',
        ReferralLangConstants.lblTotalEarnings: 'एकूण रेफरल कमाई',
        ReferralLangConstants.lblReferYourFriends: 'तुमच्या मित्रांना सोप्या \nस्टेप्समध्ये रेफर करा',
        ReferralLangConstants.btnReferAndEarnNow: 'आताच रेफर करा आणि कमवा! 💸',
        ReferralLangConstants.lblYourReferrals: 'तुमचे रेफरल्स',
        ReferralLangConstants.headReferralDetails: 'रेफरल तपशील',
        ReferralLangConstants.btnRemindFriends: 'मित्राला आठवण करून द्या',
        ReferralLangConstants.msgHelpFriends: 'तुमच्या मित्राला माईलस्टोन्स पूर्ण करण्यास मदत करा आणि मिळवा ',
        ReferralLangConstants.lblCampaignExpired: 'कॅम्पेन संपले आहे',
        ReferralLangConstants.headAvailableOffers: 'उपलब्ध ऑफर्स',
        ReferralLangConstants.lblSelectHighEarningReferral: 'जास्त कमाई देणारे रेफरल निवडा आणि मित्रांसोबत शेअर करा',
        ReferralLangConstants.lblSearchPincodeHub: 'हबचे नाव किंवा पिनकोडने शोधा',
        ReferralLangConstants.lblOfferValidHubList: 'ऑफर असलेल्या हबची यादी',
        ReferralLangConstants.btnShare: 'शेअर करा',
        ReferralLangConstants.lblEarnUpto: 'मिळवा पर्यंत',
        ReferralLangConstants.lblExpiryDate: 'मुदत संपण्याची तारीख : ',
        ReferralLangConstants.msgSelectReferralCampaign: 'तुम्हाला मित्रांसोबत शेअर करायची असलेली रेफरल ऑफर निवडा',
        ReferralLangConstants.msgShareWithFriends: 'तुमची रेफरल लिंक पाठवा आणि तुमच्या मित्राला Kaptaan म्हणून सामील होण्यास मदत करा',
        ReferralLangConstants.lblEnjoyBonus: 'रेफरल बोनसचा आनंद घ्या',
        ReferralLangConstants.msgEnjoyBonus: 'तुमच्या मित्राने आवश्यक ऑर्डर्स पूर्ण केल्यावर तुम्हाला तुमचा बोनस मिळेल',
        ReferralLangConstants.lblSelectReferralCampaign: 'रेफरल कॅम्पेन निवडा',
        ReferralLangConstants.lblShareWithFriends: 'तुमच्या मित्रासोबत शेअर करा',
        ReferralLangConstants.lblOfferValidHub: 'ऑफरसाठी पात्र हब',
        ReferralLangConstants.lblJoiningBonus: 'जॉइनिंग बोनस',
        ReferralLangConstants.lblMilestonesUpdated: 'माईलस्टोन्स दररोज मध्यरात्री अपडेट केले जातात ',
        ReferralLangConstants.lblNoHubsAvailable: 'एकही हब उपलब्ध नाही',
        ReferralLangConstants.msgMoreOnThis: ' या रेफरलवर अधिक!',
        ReferralLangConstants.lblReferMoreFriends: 'आणखी मित्रांना रेफर करा आणि कमवा ',
        ReferralLangConstants.lblPerReferral: ' प्रति रेफरल',
        ReferralLangConstants.lblNoCampaignsAvailable: 'कोणतेही कॅम्पेन उपलब्ध नाही',
        ReferralLangConstants.lblLateNote: 'अरेरे! तुमचा मित्र थोडा उशिरा सामील झाला आहे असे वाटते, काळजी करू नका तरीही तुम्हाला या रेफरलसाठी कमाई मिळेल',
        ReferralLangConstants.msgReferralNotEligible: 'रेफरल पात्र नाही — तुमचा मित्र संबंधित हब किंवा Blitz सोबत सक्रिय नाही',
        ReferralLangConstants.lblNoGoalsAvailable: 'एकही उद्दिष्ट (Goals) उपलब्ध नाही',
        ReferralLangConstants.lblWrongNodeNote: 'तुमचा मित्र दुसऱ्या हबमध्ये सामील झाला आहे, तरीही तुम्ही बेस रिवॉर्डसाठी पात्र आहात.',
        ReferralLangConstants.btnViewReferral: 'रेफरल कॅम्पेन पहा 💸',
        ReferralLangConstants.msgTrackReferralEarnings: 'तुम्ही तुमची रेफरल कमाई येथे ट्रॅक करू शकता',
        ReferralLangConstants.btnWatchHowItWorks: 'कसे ते पहा',
        ReferralLangConstants.lblSelectCampaign: 'कॅम्पेन\nनिवडा',
        ReferralLangConstants.lblReferYourFriend: 'मित्राला\nरेफर करा',
        ReferralLangConstants.lblTrackYourBonus: 'बोनस\nट्रॅक करा',
        ReferralLangConstants.lblOfferDetails: 'ऑफर तपशील',
        ReferralLangConstants.lblHubList: 'हब यादी',
        ReferralLangConstants.lblMilestones: 'माईलस्टोन्स',
      };
}