import 'shipment_lang_constants.dart';

class ShipmentTaIn {
  static Map<String, String> get translations => {
        ShipmentLangConstants.headPickupDetails: 'பிக்கப் விவரங்கள்',
        ShipmentLangConstants.headTaskDetails: 'டாஸ்க் விவரங்கள்',
        ShipmentLangConstants.headShipmentDetails: 'ஷிப்மென்ட் விவரங்கள்',
        ShipmentLangConstants.lblReturnOrder: 'ரிட்டர்ன் ஆர்டர்',
        ShipmentLangConstants.lblStartQc: 'QC தொடங்கவும்',
        ShipmentLangConstants.lblResumeOrder: 'ஸ்கேனைத் தொடரவும்',
        ShipmentLangConstants.lblScanOrder: 'ஆர்டரை ஸ்கேன் செய்யவும்',
        ShipmentLangConstants.lblDeliverOrder: 'ஆர்டரை டெலிவரி செய்யவும்',
        ShipmentLangConstants.lblEnterAreaToDeliverOrder: 'டெலிவரி செய்ய ஏரியாவிற்குள் நுழையவும்',
        ShipmentLangConstants.headFailedDelivered: 'டெலிவரி தோல்வியடைந்தது',
        ShipmentLangConstants.msgFailedDelivered: 'ஆர்டர் டெலிவரி தோல்வியடைந்ததாகப் பதிவு செய்யப்பட்டுள்ளது',
        ShipmentLangConstants.msgUnableToLaunchNavigation: 'நேவிகேஷனைத் தொடங்க முடியவில்லை',
        ShipmentLangConstants.headSameLocationOrders: 'ஒரே இடத்திலுள்ள ஆர்டர்கள்',
        ShipmentLangConstants.msgNoNearbyShipments: 'டெலிவரி செய்ய அருகில் ஷிப்மென்ட்கள் எதுவும் இல்லை',
        ShipmentLangConstants.headNearbyShipmentsToDeliver: 'டெலிவரி செய்ய அருகிலுள்ள ஷிப்மென்ட்கள்',
        ShipmentLangConstants.msgCanCompleteAnyOrdersBelow: 'கீழேயுள்ள எந்த ஆர்டரையும் நீங்கள் முடிக்கலாம்',
        ShipmentLangConstants.lblQuickPickupWithScanOtp: 'OTP/ஸ்கேன் மூலம் பிக்கப்பை உறுதிப்படுத்தவும்',
        ShipmentLangConstants.msgQuickPickupScanOTP: 'தயவுசெய்து அனைத்து ஷிப்மென்ட்களையும் வரிசையாக உறுதிப்படுத்தவும்',
        ShipmentLangConstants.lblVerifyOrder: 'ஆர்டரை உறுதிப்படுத்து',
        ShipmentLangConstants.lblMarkPickupFailed: 'பிக்கப் தோல்வியடைந்ததாகக் குறிக்கவும்',
        ShipmentLangConstants.lblCompletePickup: 'பிக்கப்பை முடிக்கவும்',
        ShipmentLangConstants.lblScanAndVerifyAll: 'ஸ்கேன் செய்து அனைத்தையும் உறுதிப்படுத்து',
        ShipmentLangConstants.lblPickupFailed: 'பிக்கப் தோல்வியடைந்தது',
        ShipmentLangConstants.lblDeliveryFailed: 'டெலிவரி தோல்வியடைந்தது',
        ShipmentLangConstants.lblOrderPickupFailed: 'ஆர்டர் பிக்கப் தோல்வியடைந்தது',
        ShipmentLangConstants.msgPickupFailedForOrder: 'ஆர்டர் {awb} பிக்கப் தோல்வியடைந்தது.\nதயவுசெய்து மற்ற ஆர்டர்களுடன் தொடரவும்.',
        ShipmentLangConstants.msgDeliveryFailedForOrder: 'ஆர்டர் {awb} டெலிவரி தோல்வியடைந்தது.\nதயவுசெய்து மற்ற ஆர்டர்களுடன் தொடரவும்.',
        ShipmentLangConstants.lblStorePickup: 'ஸ்டோர் பிக்கப்',
        ShipmentLangConstants.lblStoreReturn: 'ஸ்டோர் ரிட்டர்ன்',
        ShipmentLangConstants.lblItemsNeedsToBePicked: 'பிக்கப் செய்ய வேண்டிய பொருட்கள்',
        ShipmentLangConstants.lblRefreshingTrip: 'ட்ரிப் புதுப்பிக்கப்படுகிறது',
        ShipmentLangConstants.lblNearOrders: 'அருகிலுள்ள ஆர்டர்கள்',
        ShipmentLangConstants.msgPickupMarkedFailed: 'பிக்கப் தோல்வியடைந்ததாகக் குறிக்கப்படுகிறது',
        ShipmentLangConstants.msgShipmentVerified: 'ஷிப்மென்ட் உறுதிப்படுத்தப்பட்டது',
        ShipmentLangConstants.lblReachLocationToActivate: 'செயல்படுத்த இடத்திற்குச் செல்லவும்',
        ShipmentLangConstants.lblToEnableDeliveryOptions: 'டெலிவரி ஆப்ஷன்களுக்கு இன்னும் {dist} உள்ளது',
        ShipmentLangConstants.lblStoreManagerDeniedPickup: 'ஸ்டோர் மேலாளர் பிக்கப் தர மறுத்துவிட்டார்',
        ShipmentLangConstants.lblStoreManagerIsNotAvailable: 'ஸ்டோர் மேலாளர் அங்கு இல்லை',
        ShipmentLangConstants.lblStoreNotAvailableAtTheLocation: 'குறிப்பிட்ட இடத்தில் ஸ்டோர் இல்லை',
        ShipmentLangConstants.lblStoreDelayingHandover: 'பொருட்களைத் தருவதில் ஸ்டோர் தாமதம் செய்கிறது',
        ShipmentLangConstants.msgTapHereToMarkOrderFailed: 'ஆர்டர் தோல்வியடைந்ததாகக் குறிக்க இங்கே ட্যাপ செய்யவும். இது முழு செயல்முறையையும் விளக்கும்.',
        ShipmentLangConstants.msgTapHereToStartDeliveryProcess: 'டெலிவரி செயல்முறையைத் தொடங்க இங்கே ட্যাপ செய்யவும். இது ஸ்கேன் செய்ய உதவும்.',
        ShipmentLangConstants.lblStartDelivery: 'டெலிவரியைத் தொடங்கு',
        ShipmentLangConstants.msgTapHereToCallUserDirectly: 'வாடிக்கையாளரை நேரடியாக அழைக்க இங்கே ட্যাপ செய்யவும்.',
        ShipmentLangConstants.msgTapHereToStartGoogleMapsNavigation: 'Google Maps நேவிகேஷனைத் தொடங்க இங்கே ட্যাপ செய்யவும்.',
        ShipmentLangConstants.msgPleaseScanAnyBarcodeToContinue: 'தொடர ஏதேனும் ஒரு பார்கோடை ஸ்கேன் செய்யவும்',
        ShipmentLangConstants.msgYouHaveMarkedGeofenceEntryForTrip: 'ட்ரிப்பிற்கான ஜியோஃபென்ஸ் என்ட்ரியைக் குறித்துள்ளீர்கள்',
        ShipmentLangConstants.msgYouHaveMarkedGeofenceEntryForTripFailed: 'ட்ริப்பிற்கான ஜியோஃபென்ஸ் என்ட்ரி தோல்வியடைந்தது',
        ShipmentLangConstants.headOrderPickupPicked: 'ஆர்டர் பிக்கப் செய்தீர்களா?',
        ShipmentLangConstants.msgOrderId: 'ஆர்டர் ID:',
      };
}