import 'shipment_lang_constants.dart';

class ShipmentTeIn {
  static Map<String, String> get translations => {
        ShipmentLangConstants.headPickupDetails: 'పికప్ వివరాలు',
        ShipmentLangConstants.headTaskDetails: 'టాస్క్ వివరాలు',
        ShipmentLangConstants.headShipmentDetails: 'షిప్‌మెంట్ వివరాలు',
        ShipmentLangConstants.lblReturnOrder: 'రిటర్న్ ఆర్డర్',
        ShipmentLangConstants.lblStartQc: 'QC ప్రారంభించండి',
        ShipmentLangConstants.lblResumeOrder: 'స్కాన్ తిరిగి ప్రారంభించండి',
        ShipmentLangConstants.lblScanOrder: 'ఆర్డర్ స్కాన్ చేయండి',
        ShipmentLangConstants.lblDeliverOrder: 'ఆర్డర్ డెలివరీ చేయండి',
        ShipmentLangConstants.lblEnterAreaToDeliverOrder: 'ఆర్డర్ డెలివరీ చేయడానికి ఏరియాలోకి ప్రవేశించండి',
        ShipmentLangConstants.headFailedDelivered: 'డెలివరీ విఫలమైంది',
        ShipmentLangConstants.msgFailedDelivered: 'ఆర్డర్ డెలివరీ విఫలమైనట్లుగా నమోదు చేయబడింది',
        ShipmentLangConstants.msgUnableToLaunchNavigation: 'నావిగేషన్ ప్రారంభించబడలేదు',
        ShipmentLangConstants.headSameLocationOrders: 'ఒకే లొకేషన్ ఆర్డర్లు',
        ShipmentLangConstants.msgNoNearbyShipments: 'డెలివరీ చేయడానికి సమీపంలో షిప్‌మెంట్‌లు లేవు',
        ShipmentLangConstants.headNearbyShipmentsToDeliver: 'డెలివరీకి సిద్ధంగా ఉన్న సమీప షిప్‌మెంట్‌లు',
        ShipmentLangConstants.msgCanCompleteAnyOrdersBelow: 'మీరు క్రింది ఆర్డర్లలో దేనినైనా పూర్తి చేయవచ్చు',
        ShipmentLangConstants.lblQuickPickupWithScanOtp: 'OTP/స్కాన్‌తో పికప్ ధృవీకరించండి',
        ShipmentLangConstants.msgQuickPickupScanOTP: 'దయచేసి అన్ని షిప్‌మెంట్‌ల పికప్‌ను వరుస క్రమంలో ధృవీకరించండి',
        ShipmentLangConstants.lblVerifyOrder: 'ఆర్డర్ ధృవీకరించండి',
        ShipmentLangConstants.lblMarkPickupFailed: 'పికప్ విఫలమైనట్లు మార్క్ చేయండి',
        ShipmentLangConstants.lblCompletePickup: 'పికప్ పూర్తి చేయండి',
        ShipmentLangConstants.lblScanAndVerifyAll: 'స్కాన్ చేసి అన్నీ ధృవీకరించండి',
        ShipmentLangConstants.lblPickupFailed: 'పికప్ విఫలమైంది',
        ShipmentLangConstants.lblDeliveryFailed: 'డెలివరీ విఫలమైంది',
        ShipmentLangConstants.lblOrderPickupFailed: 'ఆర్డర్ పికప్ విఫలమైంది',
        ShipmentLangConstants.msgPickupFailedForOrder: 'ఆర్డర్ {awb} పికప్ విఫలమైంది.\nదయచేసి మిగిలిన ఆర్డర్లతో కొనసాగండి.',
        ShipmentLangConstants.msgDeliveryFailedForOrder: 'ఆర్డర్ {awb} డెలివరీ విఫలమైంది.\nదయచేసి మిగిలిన ఆర్డర్లతో కొనసాగండి.',
        ShipmentLangConstants.lblStorePickup: 'స్టోర్ పికప్',
        ShipmentLangConstants.lblStoreReturn: 'స్టోర్ రిటర్న్',
        ShipmentLangConstants.lblItemsNeedsToBePicked: 'పికప్ చేయవలసిన ఐటమ్స్',
        ShipmentLangConstants.lblRefreshingTrip: 'ట్రిప్ రీఫ్రెష్ అవుతోంది',
        ShipmentLangConstants.lblNearOrders: 'సమీప ఆర్డర్లు',
        ShipmentLangConstants.msgPickupMarkedFailed: 'పికప్ విఫలమైనట్లు మార్క్ చేయబడుతోంది',
        ShipmentLangConstants.msgShipmentVerified: 'షిప్‌మెంట్ ధృవీకరించబడింది',
        ShipmentLangConstants.lblReachLocationToActivate: 'యాక్టివేట్ చేయడానికి లొకేషన్‌కు చేరుకోండి',
        ShipmentLangConstants.lblToEnableDeliveryOptions: 'డెలివరీ ఆప్షన్ల కోసం ఇంకా {dist} వెళ్ళాలి',
        ShipmentLangConstants.lblStoreManagerDeniedPickup: 'స్టోర్ మేనేజర్ పికప్‌ను నిరాకరించారు',
        ShipmentLangConstants.lblStoreManagerIsNotAvailable: 'స్టోర్ మేనేజర్ అందుబాటులో లేరు',
        ShipmentLangConstants.lblStoreNotAvailableAtTheLocation: 'ఈ లొకేషన్‌లో స్టోర్ అందుబాటులో లేదు',
        ShipmentLangConstants.lblStoreDelayingHandover: 'స్టోర్ ఆర్డర్ ఇవ్వడంలో ఆలస్యం చేస్తోంది',
        ShipmentLangConstants.msgTapHereToMarkOrderFailed: 'ఆర్డర్ విఫలమైనట్లు మార్క్ చేయడానికి ఇక్కడ ట్యాప్ చేయండి. ఇది మీకు ప్రాసెస్ వివరిస్తుంది.',
        ShipmentLangConstants.msgTapHereToStartDeliveryProcess: 'డెలివరీ ప్రక్రియను ప్రారంభించడానికి ఇక్కడ ట్యాప్ చేయండి. ఇది స్కాన్ చేయడానికి సహాయపడుతుంది.',
        ShipmentLangConstants.lblStartDelivery: 'డెలివరీ ప్రారంభించండి',
        ShipmentLangConstants.msgTapHereToCallUserDirectly: 'కస్టమర్‌కు నేరుగా కాల్ చేయడానికి ఇక్కడ ట్యాప్ చేయండి.',
        ShipmentLangConstants.msgTapHereToStartGoogleMapsNavigation: 'Google Maps నావిగేషన్ ప్రారంభించడానికి ఇక్కడ ట్యాప్ చేయండి.',
        ShipmentLangConstants.msgPleaseScanAnyBarcodeToContinue: 'కొనసాగించడానికి దయచేసి ఏదైనా బార్‌కోడ్ స్కాన్ చేయండి',
        ShipmentLangConstants.msgYouHaveMarkedGeofenceEntryForTrip: 'మీరు ట్రిప్ కోసం జియోఫెన్స్ ఎంట్రీ మార్క్ చేశారు',
        ShipmentLangConstants.msgYouHaveMarkedGeofenceEntryForTripFailed: 'ట్రిప్ కోసం జియోఫెన్స్ ఎంట్రీ విఫలమైంది',
        ShipmentLangConstants.headOrderPickupPicked: 'ఆర్డర్ పికప్ చేశారా?',
        ShipmentLangConstants.msgOrderId: 'ఆర్డర్ ID:',
      };
}