import 'shipment_lang_constants.dart';

class ShipmentPaIn {
  static Map<String, String> get translations => {
        ShipmentLangConstants.headPickupDetails: 'ਪਿਕਅੱਪ ਵੇਰਵੇ',
        ShipmentLangConstants.headTaskDetails: 'ਟਾਸਕ ਵੇਰਵੇ',
        ShipmentLangConstants.headShipmentDetails: 'ਸ਼ਿਪਮੈਂਟ ਵੇਰਵੇ',
        ShipmentLangConstants.lblReturnOrder: 'ਰਿਟਰਨ ਆਰਡਰ',
        ShipmentLangConstants.lblStartQc: 'QC ਸ਼ੁਰੂ ਕਰੋ',
        ShipmentLangConstants.lblResumeOrder: 'ਸਕੈਨ ਮੁੜ ਸ਼ੁਰੂ ਕਰੋ',
        ShipmentLangConstants.lblScanOrder: 'ਆਰਡਰ ਸਕੈਨ ਕਰੋ',
        ShipmentLangConstants.lblDeliverOrder: 'ਆਰਡਰ ਡਿਲੀਵਰ ਕਰੋ',
        ShipmentLangConstants.lblEnterAreaToDeliverOrder: 'ਆਰਡਰ ਡਿਲੀਵਰ ਕਰਨ ਲਈ ਏਰੀਏ ਵਿੱਚ ਦਾਖਲ ਹੋਵੋ',
        ShipmentLangConstants.headFailedDelivered: 'ਡਿਲੀਵਰੀ ਫੇਲ੍ਹ ਹੋਈ',
        ShipmentLangConstants.msgFailedDelivered: 'ਆਰਡਰ ਦੀ ਡਿਲੀਵਰੀ ਫੇਲ੍ਹ ਵਜੋਂ ਦਰਜ ਕੀਤੀ ਗਈ ਹੈ',
        ShipmentLangConstants.msgUnableToLaunchNavigation: 'ਨੇਵੀਗੇਸ਼ਨ ਸ਼ੁਰੂ ਨਹੀਂ ਹੋ ਸਕੀ',
        ShipmentLangConstants.headSameLocationOrders: 'ਇੱਕੋ ਲੋਕੇਸ਼ਨ ਦੇ ਆਰਡਰ',
        ShipmentLangConstants.msgNoNearbyShipments: 'ਡਿਲੀਵਰ ਕਰਨ ਲਈ ਨੇੜੇ ਕੋਈ ਸ਼ਿਪਮੈਂਟ ਨਹੀਂ ਹੈ',
        ShipmentLangConstants.headNearbyShipmentsToDeliver: 'ਡਿਲੀਵਰ ਕਰਨ ਲਈ ਨੇੜਲੇ ਸ਼ਿਪਮੈਂਟ',
        ShipmentLangConstants.msgCanCompleteAnyOrdersBelow: 'ਤੁਸੀਂ ਹੇਠਾਂ ਦਿੱਤੇ ਕਿਸੇ ਵੀ ਆਰਡਰ ਨੂੰ ਪੂਰਾ ਕਰ ਸਕਦੇ ਹੋ',
        ShipmentLangConstants.lblQuickPickupWithScanOtp: 'OTP/ਸਕੈਨ ਨਾਲ ਪਿਕਅੱਪ ਵੈਰੀਫਾਈ ਕਰੋ',
        ShipmentLangConstants.msgQuickPickupScanOTP: 'ਕਿਰਪਾ ਕਰਕੇ ਸਾਰੀਆਂ ਸ਼ਿਪਮੈਂਟਾਂ ਦਾ ਪਿਕਅੱਪ ਇੱਕ-ਇੱਕ ਕਰਕੇ ਵੈਰੀਫਾਈ ਕਰੋ',
        ShipmentLangConstants.lblVerifyOrder: 'ਆਰਡਰ ਵੈਰੀਫਾਈ ਕਰੋ',
        ShipmentLangConstants.lblMarkPickupFailed: 'ਪਿਕਅੱਪ ਫੇਲ੍ਹ ਮਾਰਕ ਕਰੋ',
        ShipmentLangConstants.lblCompletePickup: 'ਪਿਕਅੱਪ ਪੂਰਾ ਕਰੋ',
        ShipmentLangConstants.lblScanAndVerifyAll: 'ਸਕੈਨ ਅਤੇ ਸਾਰੇ ਵੈਰੀਫਾਈ ਕਰੋ',
        ShipmentLangConstants.lblPickupFailed: 'ਪਿਕਅੱਪ ਫੇਲ੍ਹ ਹੋਇਆ',
        ShipmentLangConstants.lblDeliveryFailed: 'ਡਿਲੀਵਰੀ ਫੇਲ੍ਹ ਹੋਈ',
        ShipmentLangConstants.lblOrderPickupFailed: 'ਆਰਡਰ ਪਿਕਅੱਪ ਫੇਲ੍ਹ ਹੋਇਆ',
        ShipmentLangConstants.msgPickupFailedForOrder: 'ਆਰਡਰ {awb} ਲਈ ਪਿਕਅੱਪ ਫੇਲ੍ਹ ਹੋ ਗਿਆ।\nਕਿਰਪਾ ਕਰਕੇ ਬਾਕੀ ਆਰਡਰਾਂ ਨਾਲ ਅੱਗੇ ਵਧੋ।',
        ShipmentLangConstants.msgDeliveryFailedForOrder: 'ਆਰਡਰ {awb} ਲਈ ਡਿਲੀਵਰੀ ਫੇਲ੍ਹ ਹੋ ਗਈ।\nਕਿਰਪਾ ਕਰਕੇ ਬਾਕੀ ਆਰਡਰਾਂ ਨਾਲ ਅੱਗੇ ਵਧੋ।',
        ShipmentLangConstants.lblStorePickup: 'ਸਟੋਰ ਪਿਕਅੱਪ',
        ShipmentLangConstants.lblStoreReturn: 'ਸਟੋਰ ਰਿਟਰਨ',
        ShipmentLangConstants.lblItemsNeedsToBePicked: 'ਪਿਕ ਕੀਤੇ ਜਾਣ ਵਾਲੇ ਆਈਟਮ',
        ShipmentLangConstants.lblRefreshingTrip: 'ਟ੍ਰਿਪ ਰਿਫ੍ਰੈਸ਼ ਹੋ ਰਹੀ ਹੈ',
        ShipmentLangConstants.lblNearOrders: 'ਨੇੜਲੇ ਆਰਡਰ',
        ShipmentLangConstants.msgPickupMarkedFailed: 'ਪਿਕਅੱਪ ਫੇਲ੍ਹ ਮਾਰਕ ਕੀਤਾ ਜਾ ਰਿਹਾ ਹੈ',
        ShipmentLangConstants.msgShipmentVerified: 'ਸ਼ਿਪਮੈਂਟ ਵੈਰੀਫਾਈ ਹੋ ਗਈ',
        ShipmentLangConstants.lblReachLocationToActivate: 'ਐਕਟੀਵੇਟ ਕਰਨ ਲਈ ਲੋਕੇਸ਼ਨ ’ਤੇ ਪਹੁੰਚੋ',
        ShipmentLangConstants.lblToEnableDeliveryOptions: 'ਡਿਲੀਵਰੀ ਵਿਕਲਪ ਚਾਲੂ ਕਰਨ ਲਈ {dist} ਬਾਕੀ',
        ShipmentLangConstants.lblStoreManagerDeniedPickup: 'ਸਟੋਰ ਮੈਨੇਜਰ ਨੇ ਪਿਕਅੱਪ ਦੇਣ ਤੋਂ ਮਨ੍ਹਾ ਕਰ ਦਿੱਤਾ',
        ShipmentLangConstants.lblStoreManagerIsNotAvailable: 'ਸਟੋਰ ਮੈਨੇਜਰ ਉਪਲਬਧ ਨਹੀਂ ਹਨ',
        ShipmentLangConstants.lblStoreNotAvailableAtTheLocation: 'ਦਿੱਤੀ ਗਈ ਲੋਕੇਸ਼ਨ ’ਤੇ ਸਟੋਰ ਨਹੀਂ ਮਿਲਿਆ',
        ShipmentLangConstants.lblStoreDelayingHandover: 'ਸਟੋਰ ਆਰਡਰ ਦੇਣ ਵਿੱਚ ਦੇਰੀ ਕਰ ਰਿਹਾ ਹੈ',
        ShipmentLangConstants.msgTapHereToMarkOrderFailed: 'ਆਰਡਰ ਫੇਲ੍ਹ ਮਾਰਕ ਕਰਨ ਲਈ ਇੱਥੇ ਟੈਪ ਕਰੋ। ਇਹ ਤੁਹਾਨੂੰ ਪੂਰੀ ਪ੍ਰਕਿਰਿਆ ਦੱਸੇਗਾ।',
        ShipmentLangConstants.msgTapHereToStartDeliveryProcess: 'ਡਿਲੀਵਰੀ ਪ੍ਰਕਿਰਿਆ ਸ਼ੁਰੂ ਕਰਨ ਲਈ ਇੱਥੇ ਟੈਪ ਕਰੋ। ਇਹ ਤੁਹਾਨੂੰ ਸਕੈਨਿੰਗ ਵਿੱਚ ਮਦਦ ਕਰੇਗਾ।',
        ShipmentLangConstants.lblStartDelivery: 'ਡਿਲੀਵਰੀ ਸ਼ੁਰੂ ਕਰੋ',
        ShipmentLangConstants.msgTapHereToCallUserDirectly: 'ਕਸਟਮਰ ਨੂੰ ਸਿੱਧਾ ਕਾਲ ਕਰਨ ਲਈ ਇੱਥੇ ਟੈਪ ਕਰੋ।',
        ShipmentLangConstants.msgTapHereToStartGoogleMapsNavigation: 'Google Maps ਨੇਵੀਗੇਸ਼ਨ ਸ਼ੁਰੂ ਕਰਨ ਲਈ ਇੱਥੇ ਟੈਪ ਕਰੋ।',
        ShipmentLangConstants.msgPleaseScanAnyBarcodeToContinue: 'ਅੱਗੇ ਵਧਣ ਲਈ ਕਿਰਪਾ ਕਰਕੇ ਕੋਈ ਵੀ ਬਾਰਕੋਡ ਸਕੈਨ ਕਰੋ',
        ShipmentLangConstants.msgYouHaveMarkedGeofenceEntryForTrip: 'ਤੁਸੀਂ ਟ੍ਰਿਪ ਲਈ ਜਿਓਫੈਂਸ ਐਂਟਰੀ ਮਾਰਕ ਕਰ ਦਿੱਤੀ ਹੈ',
        ShipmentLangConstants.msgYouHaveMarkedGeofenceEntryForTripFailed: 'ਟ੍ਰਿਪ ਲਈ ਜਿਓਫੈਂਸ ਐਂਟਰੀ ਫੇਲ੍ਹ ਹੋ ਗਈ',
        ShipmentLangConstants.headOrderPickupPicked: 'ਆਰਡਰ ਪਿਕਅੱਪ ਕਰ ਲਿਆ?',
        ShipmentLangConstants.msgOrderId: 'ਆਰਡਰ ID:',
      };
}