import 'shipment_lang_constants.dart';

class ShipmentMrIn {
  static Map<String, String> get translations => {
        ShipmentLangConstants.headPickupDetails: 'पिकअप तपशील',
        ShipmentLangConstants.headTaskDetails: 'टास्क तपशील',
        ShipmentLangConstants.headShipmentDetails: 'शिपमेंट तपशील',
        ShipmentLangConstants.lblReturnOrder: 'रिटर्न ऑर्डर',
        ShipmentLangConstants.lblStartQc: 'QC सुरू करा',
        ShipmentLangConstants.lblResumeOrder: 'स्कॅन पुन्हा सुरू करा',
        ShipmentLangConstants.lblScanOrder: 'ऑर्डर स्कॅन करा',
        ShipmentLangConstants.lblDeliverOrder: 'ऑर्डर डिलिव्हर करा',
        ShipmentLangConstants.lblEnterAreaToDeliverOrder: 'ऑर्डर डिलिव्हर करण्यासाठी एरियामध्ये प्रवेश करा',
        ShipmentLangConstants.headFailedDelivered: 'डिलिव्हरी अयशस्वी',
        ShipmentLangConstants.msgFailedDelivered: 'ऑर्डर डिलिव्हरी अयशस्वी म्हणून नोंदवली गेली आहे',
        ShipmentLangConstants.msgUnableToLaunchNavigation: 'नेव्हिगेशन सुरू होऊ शकले नाही',
        ShipmentLangConstants.headSameLocationOrders: 'एकाच लोकेशनच्या ऑर्डर्स',
        ShipmentLangConstants.msgNoNearbyShipments: 'डिलिव्हर करण्यासाठी जवळ कोणतेही शिपमेंट नाही',
        ShipmentLangConstants.headNearbyShipmentsToDeliver: 'डिलिव्हर करण्यासाठी जवळचे शिपमेंट्स',
        ShipmentLangConstants.msgCanCompleteAnyOrdersBelow: 'तुम्ही खालीलपैकी कोणतीही ऑर्डर पूर्ण करू शकता',
        ShipmentLangConstants.lblQuickPickupWithScanOtp: 'OTP/स्कॅनने पिकअप व्हेरिफाय करा',
        ShipmentLangConstants.msgQuickPickupScanOTP: 'कृपया सर्व शिपमेंट्सचा पिकअप एकामागून एक क्रमाने व्हेरिफाय करा',
        ShipmentLangConstants.lblVerifyOrder: 'ऑर्डर व्हेरिफाय करा',
        ShipmentLangConstants.lblMarkPickupFailed: 'पिकअप अयशस्वी नोंदवा',
        ShipmentLangConstants.lblCompletePickup: 'पिकअप पूर्ण करा',
        ShipmentLangConstants.lblScanAndVerifyAll: 'स्कॅन आणि सर्व व्हेरिफाय करा',
        ShipmentLangConstants.lblPickupFailed: 'पिकअप अयशस्वी',
        ShipmentLangConstants.lblDeliveryFailed: 'डिलिव्हरी अयशस्वी',
        ShipmentLangConstants.lblOrderPickupFailed: 'ऑर्डर पिकअप अयशस्वी',
        ShipmentLangConstants.msgPickupFailedForOrder: 'ऑर्डर {awb} साठी पिकअप अयशस्वी झाला.\nकृपया इतर ऑर्डर्ससह पुढे जा.',
        ShipmentLangConstants.msgDeliveryFailedForOrder: 'ऑर्डर {awb} साठी डिलिव्हरी अयशस्वी झाली.\nकृपया इतर ऑर्डर्ससह पुढे जा.',
        ShipmentLangConstants.lblStorePickup: 'स्टोअर पिकअप',
        ShipmentLangConstants.lblStoreReturn: 'स्टोअर रिटर्न',
        ShipmentLangConstants.lblItemsNeedsToBePicked: 'पिकअप करायचे आयटम्स',
        ShipmentLangConstants.lblRefreshingTrip: 'ट्रिप रिफ्रेश होत आहे',
        ShipmentLangConstants.lblNearOrders: 'जवळील ऑर्डर्स',
        ShipmentLangConstants.msgPickupMarkedFailed: 'पिकअप अयशस्वी म्हणून नोंदवला जात आहे',
        ShipmentLangConstants.msgShipmentVerified: 'शिपमेंट व्हेरिफाय झाले',
        ShipmentLangConstants.lblReachLocationToActivate: 'ॲक्टिव्हेट करण्यासाठी लोकेशनवर पोहोचा',
        ShipmentLangConstants.lblToEnableDeliveryOptions: 'डिलिव्हरी पर्याय सुरू करण्यासाठी {dist} बाकी',
        ShipmentLangConstants.lblStoreManagerDeniedPickup: 'स्टोअर मॅनेजरने पिकअप देण्यास नकार दिला',
        ShipmentLangConstants.lblStoreManagerIsNotAvailable: 'स्टोअर मॅनेजर उपलब्ध नाहीत',
        ShipmentLangConstants.lblStoreNotAvailableAtTheLocation: 'दिलेल्या लोकेशनवर स्टोअर उपलब्ध नाही',
        ShipmentLangConstants.lblStoreDelayingHandover: 'स्टोअर ऑर्डर देण्यास उशीर करत आहे',
        ShipmentLangConstants.msgTapHereToMarkOrderFailed: 'ऑर्डर अयशस्वी नोंदवण्यासाठी येथे टॅप करा. हे तुम्हाला ऑर्डर फेल करण्याची प्रक्रिया सांगेल.',
        ShipmentLangConstants.msgTapHereToStartDeliveryProcess: 'डिलिव्हरी प्रक्रिया सुरू करण्यासाठी येथे टॅप करा. हे तुम्हाला स्कॅनिंग आणि डिलिव्हरी प्रक्रियेत मदत करेल.',
        ShipmentLangConstants.lblStartDelivery: 'डिलिव्हरी सुरू करा',
        ShipmentLangConstants.msgTapHereToCallUserDirectly: 'कस्टमरला थेट कॉल करण्यासाठी येथे टॅप करा. यामुळे तुम्हाला पिकअप किंवा डिलिव्हरीसाठी समन्वय साधता येईल.',
        ShipmentLangConstants.msgTapHereToStartGoogleMapsNavigation: 'Google Maps नेव्हिगेशन सुरू करण्यासाठी येथे टॅप करा.',
        ShipmentLangConstants.msgPleaseScanAnyBarcodeToContinue: 'पुढे जाण्यासाठी कृपया कोणताही बारकोड स्कॅन करा',
        ShipmentLangConstants.msgYouHaveMarkedGeofenceEntryForTrip: 'तुम्ही ट्रिपसाठी जिओफेन्स एन्ट्री मार्क केली आहे',
        ShipmentLangConstants.msgYouHaveMarkedGeofenceEntryForTripFailed: 'ट्रिपसाठी जिओफेन्स एन्ट्री अयशस्वी झाली',
        ShipmentLangConstants.headOrderPickupPicked: 'ऑर्डर पिकअप केली का?',
        ShipmentLangConstants.msgOrderId: 'ऑर्डर ID:',
      };
}