import 'profile_lang_constants.dart';

class ProfileTeIn {
  static Map<String, String> get translations => {
        ProfileLangConstants.headProfile: 'ప్రొఫైల్',
        ProfileLangConstants.lblRating: 'రేటింగ్',
        ProfileLangConstants.lblDelivery: 'డెలివరీ',
        ProfileLangConstants.headMyQr: 'నా QR',
        ProfileLangConstants.lblSetUpYourQr: 'మొత్తాన్ని సేకరించడానికి మీ వ్యక్తిగత QRని సెటప్ చేయండి',
        ProfileLangConstants.headEnterYourUpiId: 'మీ UPI ఐడిని నమోదు చేయండి',
        ProfileLangConstants.lblEnterUpiId: 'UPI ఐడిని నమోదు చేయండి',
        ProfileLangConstants.headSelfQrAdded: 'సొంత QR జోడించబడింది',
        ProfileLangConstants.msgTheQrCodeHasBeenAddedSuccessfully: 'QR కోడ్ విజయవంతంగా జోడించబడింది',
        ProfileLangConstants.headPreview: 'ప్రివ్యూ',
        ProfileLangConstants.lblChangeUpiId: 'UPI ఐడిని మార్చండి',
        ProfileLangConstants.lblOpenPspAndCopyUpiId: 'మీ PSP (Paytm/PhonePe/GPay మొదలైనవి) తెరిచి UPI ఐడిని కాపీ చేయండి',
        ProfileLangConstants.lblClickOnChangeUpiIdToChangeUpiId: '“UPI ఐడిని మార్చండి” పై క్లిక్ చేసి, కాపీ చేసిన ఐడిని నమోదు చేయండి',
        ProfileLangConstants.lblReVerifyTwiceAndClickSubmit: 'UPI ఐడి మార్చడానికి రెండుసార్లు ధృవీకరించి సబ్మిట్ చేయండి',
        ProfileLangConstants.lblInvalidUpiId: 'చెల్లని UPI ఐడి',
        ProfileLangConstants.lblEnableQuickComOrders: 'క్విక్ కామర్స్ ఆర్డర్లను ప్రారంభించండి',
        ProfileLangConstants.lblWaitForTheOrders: 'ఆర్డర్ల కోసం వేచి ఉండండి....',
        ProfileLangConstants.lblEarnMoreWithFasterDeliveries: 'వేగవంతమైన డెలివరీలతో మరింత సంపాదించండి',
        ProfileLangConstants.headFuelPayout: 'ఫ్యూయల్ పేఅవుట్',
        ProfileLangConstants.lblSeeFuelPayoutHistory: 'ఫ్యూయల్ పేఅవుట్ చరిత్రను చూడండి',
        ProfileLangConstants.headReferAndEarn: 'రిఫర్ చేయండి మరియు సంపాదించండి',
        ProfileLangConstants.msgReferAndEarn: 'మీ స్నేహితుడిని రిఫర్ చేయండి మరియు ₹25,000 వరకు సంపాదించండి',
        ProfileLangConstants.headLanguageSettings: 'భాషా సెట్టింగ్‌లు',
        ProfileLangConstants.msgLanguageSettings: 'మీ భాషా ప్రాధాన్యతలను నిర్వహించండి',
        ProfileLangConstants.lblManageLanguage: 'భాషను నిర్వహించండి',
        ProfileLangConstants.headSelectLanguage: 'భాషను ఎంచుకోండి',
        ProfileLangConstants.msgChangingTheLanguageApplyToEntireApp: 'భాషను మార్చడం మొత్తం యాప్‌కు వర్తిస్తుంది.',
        ProfileLangConstants.lblLanguageUpdated: 'భాష అప్‌డేట్ చేయబడింది',
        ProfileLangConstants.lblLanguageAppliedToTheEntireApp: 'మీ ప్రాధాన్యత భాష యాప్ మొత్తానికి వర్తింపజేయబడింది',
        ProfileLangConstants.msgThisWillPersonaliseYourExperience: 'ఇది మీ అనుభవాన్ని మెరుగుపరచడానికి ఉపయోగించబడుతుంది',
        ProfileLangConstants.headLogoutYourAccount: 'మీ అకౌంట్ నుండి లాగ్ అవుట్ చేయండి',
        ProfileLangConstants.lblDoYouWantToLogout: 'మీరు ఈ పరికరం నుండి లాగ్ అవుట్ చేయాలనుకుంటున్నారా?',
        ProfileLangConstants.lblLogout: 'లాగ్ అవుట్',
        ProfileLangConstants.lblStayLoggedIn: 'లేదు, లాగిన్ అయి ఉండండి',
      };
}