import 'profile_lang_constants.dart';

class ProfileMrIn {
  static Map<String, String> get translations => {
        ProfileLangConstants.headProfile: 'प्रोफाईल',
        ProfileLangConstants.lblRating: 'रेटिंग',
        ProfileLangConstants.lblDelivery: 'डिलिव्हरी',
        ProfileLangConstants.headMyQr: 'माझा QR',
        ProfileLangConstants.lblSetUpYourQr: 'रक्कम गोळा करण्यासाठी तुमचा वैयक्तिक QR सेट करा',
        ProfileLangConstants.headEnterYourUpiId: 'तुमचा UPI आयडी टाका',
        ProfileLangConstants.lblEnterUpiId: 'UPI आयडी टाका',
        ProfileLangConstants.headSelfQrAdded: 'स्वतःचा QR जोडला गेला',
        ProfileLangConstants.msgTheQrCodeHasBeenAddedSuccessfully: 'QR कोड यशस्वीरित्या जोडला गेला आहे',
        ProfileLangConstants.headPreview: 'प्रिव्ह्यू',
        ProfileLangConstants.lblChangeUpiId: 'UPI आयडी बदला',
        ProfileLangConstants.lblOpenPspAndCopyUpiId: 'तुमचे PSP (Paytm/PhonePe/GPay इ.) उघडा आणि UPI आयडी कॉपी करा',
        ProfileLangConstants.lblClickOnChangeUpiIdToChangeUpiId: '“UPI आयडी बदला” वर क्लिक करा आणि कॉपी केलेला UPI आयडी इनपुट बॉक्समध्ये टाका',
        ProfileLangConstants.lblReVerifyTwiceAndClickSubmit: 'UPI आयडी बदलण्यासाठी आणि QR सेट करण्यासाठी पुन्हा दोनदा तपासा आणि सबमिटवर क्लिक करा',
        ProfileLangConstants.lblInvalidUpiId: 'अवैध UPI आयडी',
        ProfileLangConstants.lblEnableQuickComOrders: 'क्विक कॉमर्स ऑर्डर्स सुरू करा',
        ProfileLangConstants.lblWaitForTheOrders: 'ऑर्डर्सची प्रतीक्षा करा....',
        ProfileLangConstants.lblEarnMoreWithFasterDeliveries: 'वेगवान डिलिव्हरीसह अधिक कमवा',
        ProfileLangConstants.headFuelPayout: 'फ्युएल पेआउट',
        ProfileLangConstants.lblSeeFuelPayoutHistory: 'फ्युएल पेआउटचा इतिहास पहा',
        ProfileLangConstants.headReferAndEarn: 'रेफर करा आणि कमवा',
        ProfileLangConstants.msgReferAndEarn: 'तुमच्या मित्राला रेफर करा आणि ₹25,000 पर्यंत कमवा',
        ProfileLangConstants.headLanguageSettings: 'भाषा सेटिंग्ज',
        ProfileLangConstants.msgLanguageSettings: 'तुमची भाषा प्राधान्ये व्यवस्थापित करा',
        ProfileLangConstants.lblManageLanguage: 'भाषा व्यवस्थापित करा',
        ProfileLangConstants.headSelectLanguage: 'भाषा निवडा',
        ProfileLangConstants.msgChangingTheLanguageApplyToEntireApp: 'पसंतीची भाषा बदलल्यास ती संपूर्ण ॲपवर लागू होईल.',
        ProfileLangConstants.lblLanguageUpdated: 'भाषा अपडेट झाली',
        ProfileLangConstants.lblLanguageAppliedToTheEntireApp: 'तुमची पसंतीची भाषा संपूर्ण ॲपवर लागू करण्यात आली आहे',
        ProfileLangConstants.msgThisWillPersonaliseYourExperience: 'हे तुमच्या अनुभवाचे वैयक्तिकीकरण करण्यासाठी वापरले जाईल',
        ProfileLangConstants.headLogoutYourAccount: 'तुमच्या अकाउंटमधून लॉग आउट करा',
        ProfileLangConstants.lblDoYouWantToLogout: 'तुम्हाला या डिव्हाइसवरून तुमचे अकाउंट लॉग आउट करायचे आहे का?',
        ProfileLangConstants.lblLogout: 'लॉग आउट',
        ProfileLangConstants.lblStayLoggedIn: 'नाही, लॉग इन रहा',
      };
}