import 'profile_lang_constants.dart';

class ProfileTaIn {
  static Map<String, String> get translations => {
        ProfileLangConstants.headProfile: 'புரொபைல்',
        ProfileLangConstants.lblRating: 'ரேட்டிங்',
        ProfileLangConstants.lblDelivery: 'டெலிவரி',
        ProfileLangConstants.headMyQr: 'எனது QR',
        ProfileLangConstants.lblSetUpYourQr: 'தொகையை வசூலிக்க உங்கள் தனிப்பட்ட QR-ஐ செட் செய்யவும்',
        ProfileLangConstants.headEnterYourUpiId: 'உங்கள் UPI ஐடியை உள்ளிடவும்',
        ProfileLangConstants.lblEnterUpiId: 'UPI ஐடியை உள்ளிடவும்',
        ProfileLangConstants.headSelfQrAdded: 'சொந்த QR சேர்க்கப்பட்டது',
        ProfileLangConstants.msgTheQrCodeHasBeenAddedSuccessfully: 'QR கோடு வெற்றிகரமாக சேர்க்கப்பட்டது',
        ProfileLangConstants.headPreview: 'முன்னோட்டம்',
        ProfileLangConstants.lblChangeUpiId: 'UPI ஐடியை மாற்றவும்',
        ProfileLangConstants.lblOpenPspAndCopyUpiId: 'உங்கள் PSP (Paytm/PhonePe/GPay போன்றவற்றை) திறந்து UPI ஐடியை காப்பி செய்யவும்',
        ProfileLangConstants.lblClickOnChangeUpiIdToChangeUpiId: '“UPI ஐடியை மாற்றவும்” என்பதைக் கிளிக் செய்து, காப்பி செய்த ஐடியை உள்ளிடவும்',
        ProfileLangConstants.lblReVerifyTwiceAndClickSubmit: 'UPI ஐடியை மாற்ற இருமுறை சரிபார்த்து சப்மிட் என்பதைக் கிளிக் செய்யவும்',
        ProfileLangConstants.lblInvalidUpiId: 'தவறான UPI ஐடி',
        ProfileLangConstants.lblEnableQuickComOrders: 'குவிக் காமர்ஸ் ஆர்டர்களை இயக்கவும்',
        ProfileLangConstants.lblWaitForTheOrders: 'ஆர்டர்களுக்காக காத்திருக்கவும்....',
        ProfileLangConstants.lblEarnMoreWithFasterDeliveries: 'வேகமான டெலிவரிகள் மூலம் அதிகம் சம்பாதிக்கவும்',
        ProfileLangConstants.headFuelPayout: 'ஃபியூயல் பேஅவுட்',
        ProfileLangConstants.lblSeeFuelPayoutHistory: 'ஃபியூயல் பேஅவுட் வரலாற்றைப் பார்க்கவும்',
        ProfileLangConstants.headReferAndEarn: 'பரிந்துரைத்து சம்பாதிக்கவும்',
        ProfileLangConstants.msgReferAndEarn: 'உங்கள் நண்பரை பரிந்துரைத்து ₹25,000 வரை சம்பாதிக்கவும்',
        ProfileLangConstants.headLanguageSettings: 'மொழி அமைப்புகள்',
        ProfileLangConstants.msgLanguageSettings: 'உங்கள் மொழி விருப்பங்களை நிர்வகிக்கவும்',
        ProfileLangConstants.lblManageLanguage: 'மொழியை மாற்றவும்',
        ProfileLangConstants.headSelectLanguage: 'மொழியைத் தேர்ந்தெடுக்கவும்',
        ProfileLangConstants.msgChangingTheLanguageApplyToEntireApp: 'மொழியை மாற்றினால் அது ஆப் முழுவதற்கும் பொருந்தும்.',
        ProfileLangConstants.lblLanguageUpdated: 'மொழி புதுப்பிக்கப்பட்டது',
        ProfileLangConstants.lblLanguageAppliedToTheEntireApp: 'நீங்கள் தேர்ந்தெடுத்த மொழி ஆப் முழுவதற்கும் பயன்படுத்தப்பட்டது',
        ProfileLangConstants.msgThisWillPersonaliseYourExperience: 'இது உங்கள் அனுபவத்தை மேம்படுத்த பயன்படுத்தப்படும்',
        ProfileLangConstants.headLogoutYourAccount: 'உங்கள் அக்கவுண்ட்டிலிருந்து லாக் அவுட் செய்யவும்',
        ProfileLangConstants.lblDoYouWantToLogout: 'இந்தச் சாதனத்திலிருந்து லாக் அவுட் செய்ய விரும்புகிறீர்களா?',
        ProfileLangConstants.lblLogout: 'லாக் அவுட்',
        ProfileLangConstants.lblStayLoggedIn: 'இல்லை, லாக் இன்னிலேயே இருக்கவும்',
      };
}