import 'profile_lang_constants.dart';

class ProfilePaIn {
  static Map<String, String> get translations => {
        ProfileLangConstants.headProfile: 'ਪ੍ਰੋਫਾਈਲ',
        ProfileLangConstants.lblRating: 'ਰੇਟਿੰਗ',
        ProfileLangConstants.lblDelivery: 'ਡਿਲੀਵਰੀ',
        ProfileLangConstants.headMyQr: 'ਮੇਰਾ QR',
        ProfileLangConstants.lblSetUpYourQr: 'ਰਕਮ ਇਕੱਠੀ ਕਰਨ ਲਈ ਆਪਣਾ ਨਿੱਜੀ QR ਸੈੱਟ ਕਰੋ',
        ProfileLangConstants.headEnterYourUpiId: 'ਆਪਣੀ UPI ਆਈਡੀ ਦਰਜ ਕਰੋ',
        ProfileLangConstants.lblEnterUpiId: 'UPI ਆਈਡੀ ਦਰਜ ਕਰੋ',
        ProfileLangConstants.headSelfQrAdded: 'ਆਪਣਾ QR ਜੋੜਿਆ ਗਿਆ',
        ProfileLangConstants.msgTheQrCodeHasBeenAddedSuccessfully: 'QR ਕੋਡ ਸਫਲਤਾਪੂਰਵਕ ਜੋੜਿਆ ਗਿਆ ਹੈ',
        ProfileLangConstants.headPreview: 'ਪ੍ਰੀਵਿਊ',
        ProfileLangConstants.lblChangeUpiId: 'UPI ਆਈਡੀ ਬਦਲੋ',
        ProfileLangConstants.lblOpenPspAndCopyUpiId: 'ਆਪਣਾ PSP (Paytm/PhonePe/GPay ਆਦਿ) ਖੋਲ੍ਹੋ ਅਤੇ UPI ਆਈਡੀ ਕਾਪੀ ਕਰੋ',
        ProfileLangConstants.lblClickOnChangeUpiIdToChangeUpiId: '“UPI ਆਈਡੀ ਬਦਲੋ” ’ਤੇ ਕਲਿੱਕ ਕਰੋ ਅਤੇ ਕਾਪੀ ਕੀਤੀ UPI ਆਈਡੀ ਦਰਜ ਕਰੋ',
        ProfileLangConstants.lblReVerifyTwiceAndClickSubmit: 'UPI ਆਈਡੀ ਬਦਲਣ ਅਤੇ QR ਸੈੱਟ ਕਰਨ ਲਈ ਦੋ ਵਾਰ ਵੈਰੀਫਾਈ ਕਰੋ ਅਤੇ ਸਬਮਿਟ ਕਰੋ',
        ProfileLangConstants.lblInvalidUpiId: 'ਗਲਤ UPI ਆਈਡੀ',
        ProfileLangConstants.lblEnableQuickComOrders: 'ਕੁਇੱਕ ਕਾਮਰਸ ਆਰਡਰ ਚਾਲੂ ਕਰੋ',
        ProfileLangConstants.lblWaitForTheOrders: 'ਆਰਡਰਾਂ ਦੀ ਉਡੀਕ ਕਰੋ....',
        ProfileLangConstants.lblEarnMoreWithFasterDeliveries: 'ਤੇਜ਼ ਡਿਲੀਵਰੀ ਨਾਲ ਜ਼ਿਆਦਾ ਕਮਾਓ',
        ProfileLangConstants.headFuelPayout: 'ਫਿਊਲ ਪੇਆਊਟ',
        ProfileLangConstants.lblSeeFuelPayoutHistory: 'ਫਿਊਲ ਪੇਆਊਟ ਹਿਸਟਰੀ ਦੇਖੋ',
        ProfileLangConstants.headReferAndEarn: 'ਰੇਫਰ ਕਰੋ ਅਤੇ ਕਮਾਓ',
        ProfileLangConstants.msgReferAndEarn: 'ਆਪਣੇ ਦੋਸਤ ਨੂੰ ਰੇਫਰ ਕਰੋ ਅਤੇ ₹25,000 ਤੱਕ ਕਮਾਓ',
        ProfileLangConstants.headLanguageSettings: 'ਭਾਸ਼ਾ ਸੈਟਿੰਗਾਂ',
        ProfileLangConstants.msgLanguageSettings: 'ਆਪਣੀ ਭਾਸ਼ਾ ਦੀ ਪਸੰਦ ਦਾ ਪ੍ਰਬੰਧਨ ਕਰੋ',
        ProfileLangConstants.lblManageLanguage: 'ਭਾਸ਼ਾ ਬਦਲੋ',
        ProfileLangConstants.headSelectLanguage: 'ਭਾਸ਼ਾ ਚੁਣੋ',
        ProfileLangConstants.msgChangingTheLanguageApplyToEntireApp: 'ਭਾਸ਼ਾ ਬਦਲਣ ਨਾਲ ਇਹ ਪੂਰੀ ਐਪ ’ਤੇ ਲਾਗੂ ਹੋ ਜਾਵੇਗੀ।',
        ProfileLangConstants.lblLanguageUpdated: 'ਭਾਸ਼ਾ ਅਪਡੇਟ ਹੋ ਗਈ',
        ProfileLangConstants.lblLanguageAppliedToTheEntireApp: 'ਤੁਹਾਡੀ ਪਸੰਦੀਦਾ ਭਾਸ਼ਾ ਪੂਰੀ ਐਪ ’ਤੇ ਲਾਗੂ ਕਰ ਦਿੱਤੀ ਗਈ ਹੈ',
        ProfileLangConstants.msgThisWillPersonaliseYourExperience: 'ਇਹ ਤੁਹਾਡੇ ਅਨੁਭਵ ਨੂੰ ਬਿਹਤਰ ਬਣਾਉਣ ਲਈ ਵਰਤਿਆ ਜਾਵੇਗਾ',
        ProfileLangConstants.headLogoutYourAccount: 'ਆਪਣੇ ਅਕਾਊਂਟ ਤੋਂ ਲੋਗ ਆਊਟ ਕਰੋ',
        ProfileLangConstants.lblDoYouWantToLogout: 'ਕੀ ਤੁਸੀਂ ਇਸ ਡਿਵਾਈਸ ਤੋਂ ਲੋਗ ਆਊਟ ਕਰਨਾ ਚਾਹੁੰਦੇ ਹੋ?',
        ProfileLangConstants.lblLogout: 'ਲੋਗ ਆਊਟ',
        ProfileLangConstants.lblStayLoggedIn: 'ਨਹੀਂ, ਲੋਗ ਇਨ ਰਹੋ',
      };
}